# Generated by Django 5.0.2 on 2024-12-04 12:38

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="دسته\u200cبندی"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="شناسه",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=255,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="توضیحات متا",
                    ),
                ),
                (
                    "page_meta",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="متای صفحه"
                    ),
                ),
                (
                    "canonical",
                    models.URLField(blank=True, null=True, verbose_name="کنونیکال"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "is_validated",
                    models.BooleanField(default=True, verbose_name="تایید/عدم تایید"),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مالک",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="blogs", to="tag.tag", verbose_name="تگ بلاگ"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "بلاگ",
                "verbose_name_plural": "بلاگ\u200cها",
            },
        ),
        migrations.CreateModel(
            name="BlogSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان بخش")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/blogs/%Y/%m/%d",
                        verbose_name="تصویر بخش",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="توضیحات بخش"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="blog.blog",
                        verbose_name="بلاگ",
                    ),
                ),
            ],
            options={
                "verbose_name": "بخش بلاگ",
                "verbose_name_plural": "بخش\u200cهای بلاگ",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CommentsBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="متن کامنت")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="تایید/عدم تایید"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.blog",
                        verbose_name="بلاگ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کامنت در مقاله",
                "verbose_name_plural": "کامنت\u200cهای مقالات",
            },
        ),
        migrations.CreateModel(
            name="BlogLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked", models.BooleanField(default=True, verbose_name="پسندیدن")),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="blog.blog",
                        verbose_name="بلاگ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پسندیدن بلاگ",
                "verbose_name_plural": "پسندیدن\u200cهای بلاگ",
                "unique_together": {("blog", "user")},
            },
        ),
    ]
