# Generated by Django 5.0.2 on 2024-11-22 04:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="شناسه",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="توضیحات")),
                ("price_per_night", models.IntegerField(verbose_name="قیمت هر شب")),
                ("bedrooms", models.IntegerField(verbose_name="تعداد اتاق خواب")),
                ("buildingsmeter", models.IntegerField(verbose_name="بنا")),
                ("floorareameters", models.IntegerField(verbose_name="زیر بنا")),
                ("guests", models.IntegerField(verbose_name="تعداد مهمان")),
                ("country", models.CharField(max_length=255, verbose_name="کشور")),
                (
                    "country_code",
                    models.CharField(max_length=10, verbose_name="کد کشور"),
                ),
                (
                    "category",
                    models.CharField(max_length=255, verbose_name="دسته\u200cبندی"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/properties/%Y/%m/%d",
                        verbose_name="0تصویر",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/properties/%Y/%m/%d",
                        verbose_name="1تصویر",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/properties/%Y/%m/%d",
                        verbose_name="2تصویر",
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/properties/%Y/%m/%d",
                        verbose_name="3تصویر",
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/properties/%Y/%m/%d",
                        verbose_name="4تصویر",
                    ),
                ),
                (
                    "image5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/properties/%Y/%m/%d",
                        verbose_name="5تصویر",
                    ),
                ),
                (
                    "image6",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/properties/%Y/%m/%d",
                        verbose_name="6تصویر",
                    ),
                ),
                (
                    "image7",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/properties/%Y/%m/%d",
                        verbose_name="7تصویر",
                    ),
                ),
                (
                    "image8",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/properties/%Y/%m/%d",
                        verbose_name="8تصویر",
                    ),
                ),
                (
                    "image9",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/properties/%Y/%m/%d",
                        verbose_name="9تصویر",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="شناسه",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateField(verbose_name="تاریخ پایان")),
                (
                    "number_of_nights",
                    models.IntegerField(verbose_name="تعداد شب\u200cها"),
                ),
                ("guests", models.IntegerField(verbose_name="تعداد مهمان\u200cها")),
                ("total_price", models.FloatField(verbose_name="قیمت کل")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
        ),
    ]
